#pragma once

#include <windows.h>

#define PROJECT_DESCRIPTION		"System Manager"
#define PROJECT_COPYRIGHT		"Copyright \xA9 2025"
#define PROJECT_FILENAME		"sysmgr.exe"
#define PROJECT_VERSION_MAJOR	0
#define PROJECT_VERSION_MINOR	1
#define PROJECT_VERSION_PATCH	0
#define PROJECT_VERSION_TWEAK	0

#define _STR(x) #x
#define STR(x) _STR(x)
#define PROJECT_VERSION				PROJECT_VERSION_MAJOR, PROJECT_VERSION_MINOR, PROJECT_VERSION_PATCH, PROJECT_VERSION_TWEAK
#define PROJECT_VERSION_STRING		STR(PROJECT_VERSION_MAJOR) "." STR(PROJECT_VERSION_MINOR) "." STR(PROJECT_VERSION_PATCH) "." STR(PROJECT_VERSION_TWEAK)
